version: "3.0"
services:
  api_service:
    image: app-mongo:0.0.1
    build:
      context: .
    container_name: mongo-cart-container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017